const caves=[
{name:'The Hollow Vein',sector:'SECTOR 04',subtitle:'A reliable starter cave with copper, iron, and quartz.',unlock:0,depth:'04–18 m',minerals:[{key:'copper',name:'Copper',value:18,strength:1,color:'#e88c5d'},{key:'iron',name:'Iron',value:28,strength:2,color:'#b8a79b'},{key:'quartz',name:'Quartz',value:35,strength:3,color:'#bde5df'}]},
{name:'Ember Hollow',sector:'SECTOR 09',subtitle:'Hot tunnels hide valuable ruby, cobalt, and emberstone.',unlock:2000,depth:'22–48 m',minerals:[{key:'copper',name:'Ruby',value:72,strength:3,color:'#f06d69'},{key:'iron',name:'Cobalt',value:88,strength:4,color:'#6e9fe2'},{key:'quartz',name:'Emberstone',value:125,strength:5,color:'#ffad5e'}]},
{name:'Frostglass Grotto',sector:'SECTOR 15',subtitle:'A frozen chamber filled with sapphire, silver, and frostglass.',unlock:3000,depth:'55–92 m',minerals:[{key:'copper',name:'Silver',value:150,strength:5,color:'#d8e6eb'},{key:'iron',name:'Sapphire',value:220,strength:6,color:'#70b9ff'},{key:'quartz',name:'Frostglass',value:300,strength:7,color:'#a9fff1'}]},
{name:'Starfall Trench',sector:'SECTOR 21',subtitle:'The deepest route. Meteor metal and void crystal await.',unlock:4000,depth:'110–180 m',minerals:[{key:'copper',name:'Sunstone',value:360,strength:7,color:'#ffc06a'},{key:'iron',name:'Meteor Metal',value:520,strength:8,color:'#d7b2ff'},{key:'quartz',name:'Void Crystal',value:780,strength:9,color:'#c79cff'}]}];
const state={cash:120,depth:12,storage:0,storageMax:12,power:1,vehicle:'on foot',cave:0,unlockedCaves:[0],haul:{},mined:{},veinTimers:{},upgrades:{pickaxe:0,storage:0,cart:0,regen:0},log:[{time:'DAY 01 · 08:10',text:'Signed on with Deepcore Mining Co. Equipment is basic, but the Hollow Vein is showing promising readings.'}]};let ores={};
const upgrades=[{id:'pickaxe',icon:'⟠',name:'Steel pickaxe',desc:'Mine richer seams with less effort.',cost:180,levels:['Rusty pickaxe','Steel pickaxe','Diamond drill','Titanium breaker','Core splitter']},{id:'storage',icon:'▱',name:'Reinforced satchel',desc:'Carry more ore before heading up.',cost:110,levels:['Canvas satchel','Reinforced satchel','Cargo pack','Mine wagon','Vault hauler']},{id:'cart',icon:'⌁',name:'Cave crawler',desc:'A compact electric rover for deeper routes.',cost:320,levels:['On foot','Cave crawler','Deep hauler','Magma runner','Core cruiser']},{id:'regen',icon:'⟳',name:'Regen beacon',desc:'Restore 1 kg in every vein on a regular cycle.',cost:260,levels:['Uncalibrated beacon','Tuned beacon','Pulse beacon','Overclocked beacon','Living beacon','Quantum beacon','Genesis beacon']}];const $=id=>document.getElementById(id);let toastTimer;
const blank=()=>({copper:0,iron:0,quartz:0});function activeCave(){return caves[state.cave]}function ensureCaveState(i){const saved=state.caveStates?.[i]||{};state.caveStates[i]={haul:{...blank(),...(saved.haul||{})},mined:{...blank(),...(saved.mined||{})},veinTimers:{...blank(),...(saved.veinTimers||{})}}}function syncCave(){ensureCaveState(state.cave);ores=Object.fromEntries(activeCave().minerals.map(m=>[m.key,m]));state.haul=state.caveStates[state.cave].haul;state.mined=state.caveStates[state.cave].mined;state.veinTimers=state.caveStates[state.cave].veinTimers}
function save(){state.caveStates[state.cave]={haul:state.haul,mined:state.mined,veinTimers:state.veinTimers};localStorage.setItem('deepcore-save',JSON.stringify(state))}function load(){const saved=localStorage.getItem('deepcore-save');if(saved)Object.assign(state,JSON.parse(saved));state.upgrades={pickaxe:0,storage:0,cart:0,regen:0,...(state.upgrades||{})};state.unlockedCaves=[...new Set([0,...(state.unlockedCaves||[])])];state.caveStates=state.caveStates||{};if(!state.caveStates[0]&&state.mined)state.caveStates[0]={haul:state.haul,mined:state.mined,veinTimers:state.veinTimers||{}};syncCave()}function money(n){return '$'+n.toLocaleString()}function regenInterval(){return [30000,15000,5000,2000,1000,500,250][state.upgrades.regen]||30000}function showToast(t){$('toast').textContent=t;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2400)}
function render(){const cave=activeCave();$('cashValue').textContent=money(state.cash);$('shopCash').textContent=money(state.cash);$('depthValue').textContent=state.depth+' m';$('depthReadout').textContent=state.depth;$('storageValue').textContent=state.storage;$('storageMax').textContent=state.storageMax;$('vehicleReadout').textContent=state.vehicle.toUpperCase();$('regenReadout').textContent=`VEINS REGEN ${regenInterval()/1000}s`;$('caveSector').textContent=`ACTIVE SITE / ${cave.sector}`;$('caveTitle').textContent=cave.name.toUpperCase();$('caveSubtitle').textContent=cave.subtitle;$('toolName').textContent=upgrades[0].levels[state.upgrades.pickaxe];$('toolPower').textContent=`Strength ${state.power} · ${state.power} kg / swing`;let value=0;Object.entries(state.haul).forEach(([k,n])=>value+=n*ores[k].value);$('haulValue').textContent=money(value);$('capacityRing').textContent=Math.round(state.storage/state.storageMax*100)+'%';renderVeins();renderCaves();renderHaul();renderObjective();renderShop();renderLog();save()}
function renderVeins(){document.querySelectorAll('.ore-node').forEach(node=>{const key=node.dataset.ore,mineral=ores[key],remaining=Math.max(0,4-(state.mined[key]||0)),locked=state.power<mineral.strength;node.innerHTML=`${key==='quartz'?'✦':key==='copper'?'◈':'◆'}<span>${mineral.name}</span><small>${locked?`Strength ${mineral.strength} required`:`${remaining} kg left`}</small>`;node.classList.toggle('mined',remaining===0);node.classList.toggle('locked',locked);node.style.setProperty('--ore',mineral.color);node.setAttribute('aria-label',locked?`${mineral.name} requires strength ${mineral.strength}`:`Mine ${mineral.name}, ${remaining} kilograms remaining`)})}
function renderCaves(){$('cavePicker').innerHTML=caves.map((c,i)=>{const unlocked=state.unlockedCaves.includes(i),active=state.cave===i;return `<button class="cave-tab ${active?'active':''} ${unlocked?'':'locked'}" data-cave="${i}"><span class="cave-tab-index">0${i+1}</span><span><strong>${c.name}</strong><small>${unlocked?(active?'CURRENT LOCATION':'TRAVEL FREE'):`UNLOCK FOR ${money(c.unlock)}`}</small></span></button>`}).join('')}
function renderHaul(){const rows=Object.entries(state.haul).filter(([,n])=>n);$('haulList').innerHTML=rows.length?rows.map(([k,n])=>`<div class="haul-row"><span class="ore-label"><b class="ore-icon" style="--ore:${ores[k].color}">◆</b>${ores[k].name}</span><strong>${n} kg · ${money(n*ores[k].value)}</strong></div>`).join(''):'<div class="empty-state">Your basket is empty.<br>Click a glowing ore node or press Space to swing.</div>'}function renderObjective(){const total=Object.values(state.haul).reduce((a,b)=>a+b,0),progress=Math.min(total,3);$('objectiveProgress').textContent=progress+' / 3 kg';$('objectiveBar').style.width=progress/3*100+'%';$('objectiveText').textContent=total>=3?'Return to surface and sell your haul':'Mine 3 kg of ore'}
function renderShop(){$('shopGrid').innerHTML=upgrades.map(u=>{const level=state.upgrades[u.id],max=level>=4,next=u.cost*(level+1),detail=u.id==='pickaxe'?`Strength ${state.power} · ${u.desc}`:u.id==='regen'?`${u.desc} Current cycle: ${regenInterval()/1000} seconds.`:u.desc;return `<article class="upgrade-card panel"><span class="eyebrow">UPGRADE ${String(level+1).padStart(2,'0')}</span><div class="upgrade-icon">${u.icon}</div><h2>${u.name}</h2><p>${max?'Maximum upgrade installed.':detail}</p><div class="upgrade-meta"><span class="upgrade-level">${u.levels[level]} · ${max?'MAX':money(next)}</span><button class="upgrade-button" data-upgrade="${u.id}" ${max||state.cash<next?'disabled':''}>${max?'INSTALLED':'BUY'}</button></div></article>`}).join('')}function renderLog(){$('logList').innerHTML=state.log.slice().reverse().map(e=>`<div class="log-entry"><time>${e.time}</time><p>${e.text}</p></div>`).join('')}function addLog(text){const d=new Date();state.log.push({time:`DAY 01 · ${d.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}`,text})}
function mine(preferred){if(state.storage>=state.storageMax)return showToast('Basket full — sell your haul at the surface.');const available=Object.keys(ores).filter(k=>state.power>=ores[k].strength&&state.mined[k]<4),key=preferred||available[Math.floor(Math.random()*available.length)];if(!key)return showToast('No accessible veins remain — upgrade your pickaxe.');if(state.power<ores[key].strength)return showToast(`${ores[key].name} requires strength ${ores[key].strength}.`);if(state.mined[key]>=4)return showToast(`${ores[key].name} vein is depleted. It will regenerate over time.`);const amount=Math.min(state.power,4-state.mined[key],state.storageMax-state.storage);state.haul[key]+=amount;state.mined[key]+=amount;state.veinTimers[key]=Date.now();state.storage+=amount;state.depth=Math.max(state.depth,state.depth+Math.floor(Math.random()*3));$('logNote').textContent=`${ores[key].name} reads strong here. Keep an eye on your capacity before pushing deeper.`;showToast(`Mined ${amount} kg of ${ores[key].name.toLowerCase()}.`);render()}
function sell(){const total=Object.entries(state.haul).reduce((sum,[k,n])=>sum+n*ores[k].value,0);if(!total)return showToast('Nothing to sell yet.');state.cash+=total;state.storage=0;Object.keys(state.haul).forEach(k=>state.haul[k]=0);Object.keys(state.mined).forEach(k=>state.mined[k]=0);Object.keys(state.veinTimers).forEach(k=>state.veinTimers[k]=0);addLog(`Sold a fresh haul for ${money(total)} from ${activeCave().name}.`);showToast(`Haul sold for ${money(total)}.`);render()}
function buy(id){const u=upgrades.find(x=>x.id===id),level=state.upgrades[id],cost=u.cost*(level+1);if(level>=4||state.cash<cost)return;state.cash-=cost;state.upgrades[id]++;if(id==='pickaxe')state.power++;if(id==='storage')state.storageMax=[12,20,32,48,68][state.upgrades.storage];if(id==='cart')state.vehicle=['on foot','cave crawler','deep hauler','magma runner','core cruiser'][state.upgrades.cart];if(id==='regen')Object.keys(state.veinTimers).forEach(k=>state.veinTimers[k]=Date.now());addLog(`Installed ${u.levels[state.upgrades[id]]}. The rig is ready for a more ambitious run.`);showToast(`${u.name} installed.`);render()}
function regenInterval(){return [30000,15000,5000,2000,1000,500,250][state.upgrades.regen]||30000}
function renderShop(){ $('shopGrid').innerHTML=upgrades.map(u=>{const level=state.upgrades[u.id],max=level>=u.levels.length-1,next=u.cost*(level+1),detail=u.id==='pickaxe'?`Strength ${state.power} · ${u.desc}`:u.id==='regen'?`${u.desc} Current cycle: ${regenInterval()/1000} seconds.`:u.desc;return `<article class="upgrade-card panel"><span class="eyebrow">UPGRADE ${String(level+1).padStart(2,'0')}</span><div class="upgrade-icon">${u.icon}</div><h2>${u.name}</h2><p>${max?'Maximum upgrade installed.':detail}</p><div class="upgrade-meta"><span class="upgrade-level">${u.levels[level]} · ${max?'MAX':money(next)}</span><button class="upgrade-button" data-upgrade="${u.id}" ${max||state.cash<next?'disabled':''}>${max?'INSTALLED':'BUY'}</button></div></article>`}).join('') }
function buy(id){const u=upgrades.find(x=>x.id===id),level=state.upgrades[id],cost=u.cost*(level+1);if(level>=u.levels.length-1||state.cash<cost)return;state.cash-=cost;state.upgrades[id]++;if(id==='pickaxe')state.power++;if(id==='storage')state.storageMax=[12,20,32,48,68][state.upgrades.storage];if(id==='cart')state.vehicle=['on foot','cave crawler','deep hauler','magma runner','core cruiser'][state.upgrades.cart];if(id==='regen')Object.keys(state.veinTimers).forEach(k=>state.veinTimers[k]=Date.now());addLog(`Installed ${u.levels[state.upgrades[id]]}. The rig is ready for a more ambitious run.`);showToast(`${u.name} installed.`);render() }
function travel(index){const cave=caves[index];if(state.unlockedCaves.includes(index)){state.caveStates[state.cave]={haul:state.haul,mined:state.mined,veinTimers:state.veinTimers};state.cave=index;state.depth=Math.max(state.depth,Number(cave.depth.split('–')[0]));syncCave();showToast(`Travelled to ${cave.name}.`);render();return}if(state.cash<cave.unlock)return showToast(`You need ${money(cave.unlock)} to unlock ${cave.name}.`);state.cash-=cave.unlock;state.unlockedCaves.push(index);state.cave=index;state.depth=Math.max(state.depth,Number(cave.depth.split('–')[0]));syncCave();addLog(`Unlocked ${cave.name}. New mineral readings are coming through.`);showToast(`${cave.name} unlocked.`);render()}
function collectOre(key){if(state.storage>=state.storageMax)return showToast('Basket full — sell your haul at the surface.');if(state.mined[key]>=4)return showToast(`${ores[key].name} vein is depleted. It will regenerate over time.`);const amount=Math.min(state.power,4-state.mined[key],state.storageMax-state.storage);state.haul[key]+=amount;state.mined[key]+=amount;state.veinTimers[key]=Date.now();state.storage+=amount;state.depth=Math.max(state.depth,state.depth+Math.floor(Math.random()*3));$('logNote').textContent=`${ores[key].name} reads strong here. Keep an eye on your capacity before pushing deeper.`;showToast(`Mined ${amount} kg of ${ores[key].name.toLowerCase()}.`);render()}
let miniGame={timer:null,key:null};function closeMiningGame(){clearTimeout(miniGame.timer);miniGame.timer=null;miniGame.key=null;$('miningOverlay').classList.add('hidden');$('targetZone').innerHTML=''}function startMiningGame(preferred){if(state.storage>=state.storageMax)return showToast('Basket full — sell your haul at the surface.');const available=Object.keys(ores).filter(k=>state.power>=ores[k].strength&&state.mined[k]<4),key=preferred||available[Math.floor(Math.random()*available.length)];if(!key)return showToast('No accessible veins remain — upgrade your pickaxe.');if(state.power<ores[key].strength)return showToast(`${ores[key].name} requires strength ${ores[key].strength}.`);if(state.mined[key]>=4)return showToast(`${ores[key].name} vein is depleted. It will regenerate over time.`);const mineral=ores[key],targetCount=2+mineral.strength,windowMs=Math.max(450,1450-mineral.strength*105);let hits=0;miniGame.key=key;$('miniTitle').textContent=`Extract ${mineral.name}`;$('miniHint').textContent=`Click ${targetCount} signals before each one fades.`;$('miningOverlay').classList.remove('hidden');function next(){clearTimeout(miniGame.timer);if(hits>=targetCount){closeMiningGame();collectOre(key);return}$('miniProgress').textContent=`TARGET ${hits+1} / ${targetCount}`;$('miniTimer').textContent=`${(windowMs/1000).toFixed(2)}s WINDOW`;const zone=$('targetZone'),button=document.createElement('button');button.className='target-button';button.type='button';button.textContent='+';button.style.left=`${8+Math.random()*78}%`;button.style.top=`${10+Math.random()*68}%`;zone.innerHTML='';zone.appendChild(button);button.addEventListener('click',()=>{hits++;next()});miniGame.timer=setTimeout(()=>{closeMiningGame();showToast(`${mineral.name} signal faded — extraction failed.`)},windowMs)}next()}
function startMiningGame(preferred){if(state.storage>=state.storageMax)return showToast('Basket full — sell your haul at the surface.');const available=Object.keys(ores).filter(k=>state.power>=ores[k].strength&&state.mined[k]<4),key=preferred||available[Math.floor(Math.random()*available.length)];if(!key)return showToast('No accessible veins remain — upgrade your pickaxe.');if(state.power<ores[key].strength)return showToast(`${ores[key].name} requires strength ${ores[key].strength}.`);if(state.mined[key]>=4)return showToast(`${ores[key].name} vein is depleted. It will regenerate over time.`);const mineral=ores[key],targetCount=2+mineral.strength,baseWindow=Math.max(700,1900-mineral.strength*100);let hits=0;miniGame.key=key;$('miniTitle').textContent=`Extract ${mineral.name}`;$('miniHint').textContent=`Click ${targetCount} signals before each one fades.`;$('miningOverlay').classList.remove('hidden');function next(){clearTimeout(miniGame.timer);if(hits>=targetCount){closeMiningGame();collectOre(key);return}const currentWindow=hits===0?baseWindow+700:baseWindow;$('miniProgress').textContent=`TARGET ${hits+1} / ${targetCount}`;$('miniTimer').textContent=`${(currentWindow/1000).toFixed(2)}s WINDOW`;const zone=$('targetZone'),button=document.createElement('button');button.className='target-button';button.type='button';button.textContent='+';button.style.left=`${8+Math.random()*72}%`;button.style.top=`${10+Math.random()*62}%`;zone.innerHTML='';zone.appendChild(button);button.addEventListener('click',()=>{hits++;next()});miniGame.timer=setTimeout(()=>{closeMiningGame();showToast(`${mineral.name} signal faded — extraction failed.`)},currentWindow)}next()}
function mine(preferred){startMiningGame(preferred)}function regenerateVeins(){const now=Date.now();let changed=false;Object.keys(ores).forEach(k=>{if(state.mined[k]>0&&now-(state.veinTimers[k]||0)>=regenInterval()){state.mined[k]--;state.veinTimers[k]=now;changed=true}});if(changed)render()}function setView(view){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('hidden',v.id!==view+'View'));document.querySelectorAll('.nav-tab').forEach(b=>b.classList.toggle('active',b.dataset.view===view))}
document.addEventListener('click',e=>{if(e.target.closest('[data-cave]'))travel(Number(e.target.closest('[data-cave]').dataset.cave));if(e.target.closest('[data-ore]'))mine(e.target.closest('[data-ore]').dataset.ore);if(e.target.closest('[data-upgrade]'))buy(e.target.closest('[data-upgrade]').dataset.upgrade);if(e.target.closest('.nav-tab'))setView(e.target.closest('.nav-tab').dataset.view)});$('mineButton').addEventListener('click',()=>mine());$('sellButton').addEventListener('click',sell);$('resetButton').addEventListener('click',()=>{if(confirm('Reset your mining company?')){localStorage.removeItem('deepcore-save');location.reload()}});document.addEventListener('keydown',e=>{if(e.code==='Space'&&document.querySelector('#mineView:not(.hidden)')&&!document.querySelector('#miningOverlay:not(.hidden)')){e.preventDefault();mine()}});load();render();setInterval(regenerateVeins,1000);
// The mini-game can be safely cancelled without consuming ore.
$('cancelMining').addEventListener('click',()=>{closeMiningGame();showToast('Mining cancelled.')});

// Four-lane falling-stone extraction game. Difficulty follows the current cave.
(() => {
  const laneKeys=['d','f','j','k']; let falling=[],frame=0,last=0,spawnAt=0,miniProgress=0,active=false;
  const level=()=>Math.min(4,state.cave+1), settings=()=>{const rarity=ores[miniGame.key]?.strength||1,rareSpawn=rarity>=3?(rarity-2)*120:0;return {speed:180,spawn:Math.max(280,1150-level()*145-(rarity-1)*165-rareSpawn),window:72}};
  const update=()=>{$('miniProgress').textContent=`PROGRESS ${Math.round(miniProgress)}%`};
  const flash=(lane,cls)=>{lane.classList.remove('mini-hit','mini-miss');void lane.offsetWidth;lane.classList.add(cls)};
  const finish=()=>{active=false;cancelAnimationFrame(frame);falling.forEach(s=>s.el.remove());falling=[];closeMiningGame()};
  const spawn=()=>{const lane=Math.floor(Math.random()*4),el=document.createElement('span'),oreColor=ores[miniGame.key]?.color||'#f1c16d';el.className='falling-stone';el.style.setProperty('--stone-color',oreColor);el.textContent='◆';$('targetZone').children[lane].querySelector('.lane-track').appendChild(el);falling.push({el,lane,y:-28})};
  function loop(now){if(!active)return;const d=settings(),dt=Math.min(40,now-last);last=now;spawnAt+=dt;if(spawnAt>=d.spawn){spawnAt=0;spawn()}const zoneY=($('targetZone').clientHeight||280)-74;let missed=false;falling=falling.filter(s=>{s.y+=d.speed*dt/1000;s.el.style.transform=`translate(-50%,${s.y}px)`;if(s.y>zoneY+d.window){miniProgress=Math.max(0,miniProgress-6);missed=true;update();flash($('targetZone').children[s.lane],'mini-miss');s.el.remove();return false}return true});if(missed&&miniProgress<=0){$('miniHint').textContent='Extraction failed — the vein was lost.';setTimeout(finish,500);return}if(miniProgress>=100){$('miniHint').textContent='Extraction complete!';setTimeout(()=>{finish();collectOre(miniGame.key)},500);return}frame=requestAnimationFrame(loop)}
  function begin(preferred){if(state.storage>=state.storageMax)return showToast('Basket full — sell your haul at the surface.');const available=Object.keys(ores).filter(k=>state.power>=ores[k].strength&&state.mined[k]<4).sort((a,b)=>ores[b].strength-ores[a].strength),key=preferred||available[0];if(!key)return showToast('No accessible veins remain — upgrade your pickaxe.');miniGame.key=key;miniProgress=0;falling=[];active=true;spawnAt=0;last=performance.now();$('miniTitle').textContent=`Extract ${ores[key].name}`;$('miniHint').textContent='Press D, F, J, or K when a stone reaches its zone.';$('targetZone').innerHTML=laneKeys.map(k=>`<div class="mine-lane" data-key="${k}"><div class="lane-track"><div class="hit-zone"></div><span class="lane-key">${k.toUpperCase()}</span></div></div>`).join('');$('miningOverlay').classList.remove('hidden');update();frame=requestAnimationFrame(loop)}
  function press(key){if(!active)return;const d=settings(),rarity=ores[miniGame.key]?.strength||1,progressPerHit=Math.max(4,14+level()*2-(rarity-1)*3),zoneY=($('targetZone').clientHeight||280)-74,index=laneKeys.indexOf(key),target=falling.filter(s=>s.lane===index).sort((a,b)=>Math.abs(a.y-zoneY)-Math.abs(b.y-zoneY))[0],lane=$('targetZone').children[index];if(target&&Math.abs(target.y-zoneY)<=d.window){target.el.remove();falling=falling.filter(s=>s!==target);miniProgress=Math.min(100,miniProgress+progressPerHit);flash(lane,'mini-hit')}else{miniProgress=Math.max(0,miniProgress-3);flash(lane,'mini-miss')}update()}
  mine=begin; document.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(active&&laneKeys.includes(k)){e.preventDefault();press(k)}if(active&&e.key==='Escape')finish()});
})();
// Keep the completed mineral key available until collectOre() records the reward.
closeMiningGame=function(){clearTimeout(miniGame.timer);miniGame.timer=null;$('miningOverlay').classList.add('hidden');$('targetZone').innerHTML=''};

// Let the player rename the prospector from the profile panel.
state.playerName=state.playerName||'JUNE DANNER';
function renderPlayerName(){const name=state.playerName.trim()||'JUNE DANNER';$('playerName').textContent=name.toUpperCase();$('playerAvatar').textContent=name.split(/\s+/).map(part=>part[0]).join('').slice(0,2).toUpperCase();}
renderPlayerName();
function editPlayerName(){const next=prompt('Enter your prospector name:',state.playerName);if(next&&next.trim()){state.playerName=next.trim().slice(0,24);renderPlayerName();save();showToast(`Name changed to ${state.playerName}.`);}}
$('playerName').addEventListener('click',editPlayerName);
$('playerName').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();editPlayerName();}});

// Extend the pickaxe path so the deepest cave can eventually be mined.
upgrades[0].levels=['Rusty pickaxe','Steel pickaxe','Diamond drill','Titanium breaker','Core splitter','Magma auger','Starforged drill','Void borer','Deepcore extractor'];
render();

// Small procedural stone sounds for the rhythm minigame.
let miniAudio;
function playStoneSound(){
  const AudioContext=window.AudioContext||window.webkitAudioContext;
  if(!AudioContext)return;
  miniAudio=miniAudio||new AudioContext();
  const now=miniAudio.currentTime,osc=miniAudio.createOscillator(),gain=miniAudio.createGain();
  osc.type='triangle'; osc.frequency.setValueAtTime(180,now); osc.frequency.exponentialRampToValueAtTime(70,now+0.09);
  gain.gain.setValueAtTime(0.0001,now); gain.gain.exponentialRampToValueAtTime(0.16,now+0.008); gain.gain.exponentialRampToValueAtTime(0.0001,now+0.11);
  osc.connect(gain); gain.connect(miniAudio.destination); osc.start(now); osc.stop(now+0.12);
}

function playStoneSound(){
  const AudioContext=window.AudioContext||window.webkitAudioContext;if(!AudioContext)return;
  miniAudio=miniAudio||new AudioContext();
  const mineral=ores[miniGame.key],name=(mineral?.name||'').toLowerCase();
  const crystal=name.includes('void crystal')||name.includes('meteor metal')||name.includes('amethyst');
  const play=()=>{const now=miniAudio.currentTime,notes=crystal?[660,990]:[260],duration=crystal?.3:.17;notes.forEach((frequency,i)=>{const osc=miniAudio.createOscillator(),gain=miniAudio.createGain();osc.type=crystal?'sine':'square';osc.frequency.setValueAtTime(frequency,now);gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(crystal?.2:.32,now+.01);gain.gain.exponentialRampToValueAtTime(.0001,now+duration);osc.connect(gain);gain.connect(miniAudio.destination);osc.start(now+i*.035);osc.stop(now+duration+i*.035)});};
  if(miniAudio.state==='suspended')miniAudio.resume().then(play);else play();
}

// Purple ores use a higher, crystalline chime instead of the regular stone hit.
function playStoneSound(){
  const AudioContext=window.AudioContext||window.webkitAudioContext;if(!AudioContext)return;
  miniAudio=miniAudio||new AudioContext();
  const mineral=ores[miniGame.key],name=(mineral?.name||'').toLowerCase(),color=(mineral?.color||'').toLowerCase();
  const purple=name.includes('amethyst')||name.includes('void')||['#c79cff','#d7b2ff','#b78cff'].includes(color);
  const chime=()=>{const now=miniAudio.currentTime,osc=miniAudio.createOscillator(),gain=miniAudio.createGain();osc.type=purple?'sine':'square';osc.frequency.setValueAtTime(purple?620:260,now);osc.frequency.exponentialRampToValueAtTime(purple?980:85,now+(purple?.22:.14));gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(purple?.22:.32,now+.01);gain.gain.exponentialRampToValueAtTime(.0001,now+(purple?.25:.16));osc.connect(gain);gain.connect(miniAudio.destination);osc.start(now);osc.stop(now+(purple?.26:.17))};
  if(miniAudio.state==='suspended')miniAudio.resume().then(chime);else chime();
}
document.addEventListener('keydown',e=>{if(document.querySelector('#miningOverlay:not(.hidden)')&&['d','f','j','k'].includes(e.key.toLowerCase()))playStoneSound()});

function playStoneSound(){
  const AudioContext=window.AudioContext||window.webkitAudioContext;if(!AudioContext)return;
  miniAudio=miniAudio||new AudioContext();
  const strike=()=>{const now=miniAudio.currentTime,osc=miniAudio.createOscillator(),gain=miniAudio.createGain();osc.type='square';osc.frequency.setValueAtTime(260,now);osc.frequency.exponentialRampToValueAtTime(85,now+0.14);gain.gain.setValueAtTime(0.0001,now);gain.gain.exponentialRampToValueAtTime(0.32,now+0.01);gain.gain.exponentialRampToValueAtTime(0.0001,now+0.16);osc.connect(gain);gain.connect(miniAudio.destination);osc.start(now);osc.stop(now+0.17)};
  if(miniAudio.state==='suspended')miniAudio.resume().then(strike);else strike();
}

// Pay the starter objective once, after the haul reaches 3 kg.
state.objectivePaid=Boolean(state.objectivePaid);
const collectOreWithObjectiveReward=collectOre;
collectOre=function(key){
  collectOreWithObjectiveReward(key);
  const total=Object.values(state.haul).reduce((sum,n)=>sum+n,0);
  if(total>=3&&!state.objectivePaid){
    state.objectivePaid=true;
    state.cash+=250;
    addLog('Completed the starter objective: mined 3 kg of ore. Bonus received: $250.');
    showToast('Objective complete — $250 bonus received!');
    render();
  }
};

const miningObjectives=[
  {goal:3,reward:250,label:'Mine 3 kg of ore'},
  {goal:7,reward:500,label:'Mine 7 kg of ore'},
  {goal:12,reward:900,label:'Mine 12 kg of ore'},
  {goal:18,reward:1500,label:'Mine 18 kg of ore'},
  {goal:25,reward:2400,label:'Mine 25 kg of ore'}
];
state.objectiveIndex=Number.isInteger(state.objectiveIndex)?state.objectiveIndex:(state.objectivePaid?1:0);
const renderObjectiveProgress=renderObjective;
renderObjective=function(){
  const objective=miningObjectives[Math.min(state.objectiveIndex,miningObjectives.length-1)];
  const total=Object.values(state.haul).reduce((sum,n)=>sum+n,0),progress=Math.min(total,objective.goal);
  $('objectiveProgress').textContent=`${progress} / ${objective.goal} kg`;
  $('objectiveBar').style.width=`${progress/objective.goal*100}%`;
  $('objectiveText').textContent=objective.label;
};
const collectOreWithObjectives=collectOre;
collectOre=function(key){
  collectOreWithObjectives(key);
  if(state.objectiveIndex===0&&state.objectivePaid){state.objectiveIndex=1;render();return;}
  const objective=miningObjectives[state.objectiveIndex],total=Object.values(state.haul).reduce((sum,n)=>sum+n,0);
  if(objective&&total>=objective.goal){
    state.cash+=objective.reward;
    addLog(`Completed objective: ${objective.label}. Bonus received: ${money(objective.reward)}.`);
    showToast(`${objective.label} complete — ${money(objective.reward)} bonus!`);
    state.objectiveIndex=Math.min(state.objectiveIndex+1,miningObjectives.length-1);
    state.objectivePaid=true;
    render();
  }
};
